title:             Cindy Wang
email:             cindywang3299@gmail.com
description:       Getting Inspired
author:            Cindy
baseurl:           ""
url:               "http://cindywang.com"

# Social Profiles
linkedin_username:  cindywang3299
github_username:    cindywang3299

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
